# Site settings
# title: Brendan F. Miller, PhD
# email: bmille79@jh.edu
# description: "Post-Doctoral Fellow. Johns Hopkins University. Molecular Biologist."
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://bmill3r.github.io/"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# for Prologue:
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brendan F. Miller, PhD
subtitle: ""
author: Brendan F. Miller, PhD
email: bmille79@jh.edu
avatar: "img/avatar.png"

# You'll want to customize url and baseurl for your own site:
# baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "http://bmill3r.github.io/"
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
# remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://www.twitter.com/bf_miller_
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/brendan-f-miller
github_url: https://github.com/bmill3r/
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Build settings
# theme: minima
# theme: jekyll-swiss
# theme_color: blue
# theme: oscailte
# remote_theme: coogie/oscailte
markdown: kramdown
# highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
